### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by radez** [jaraco/rst.linker#5]
Trying to package this to get Fedora's CherryPy up to lastest version in fedora, need a LICENSE file to declare in the package.

**Comment by radez** [comment]
nm, just saw you're skeleton discussion

**Comment by jaraco** [comment]
I'll pull in the latest skeleton to include the license.

**Comment by jaraco** [comment]
1.10 includes the license file.

**Comment by radez** [comment]
Thank you!
