### ISSUE TITLE
Set `parallel_read_safe` in plugin metadata

### ISSUE THREAD

**Issue by webknjaz** [jaraco/rst.linker#7]
Sphinx is unhappy when `-j auto` is used.

```console
Warning, treated as error:
the rst.linker extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
```

Needs smth like this: https://github.com/ansible/ansible/blame/505c99265ca6e9c75a3c9793b999cbdc46de1956/docs/docsite/_extensions/pygments_lexer.py#L187

**Comment by jaraco** [comment]
Hmm. There's a non-zero chance this library is not parallel safe. I'll have to read up more on it.

**Comment by jaraco** [comment]
The docs don't really specify what guarantees are needed to be safe for parallel reads. I'm going to assume it's safe and we'll see what breaks.
